# Numpy memo

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np

![Numpy Axes](https://vrzkj25a871bpq7t1ugcgmn9-wpengine.netdna-ssl.com/wp-content/uploads/2018/11/numpy-arrays-have-axes.png "Numpy axes")

In [2]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((0,3))

array([], shape=(0, 3), dtype=float64)

In [24]:
np_array_2d = np.arange(0, 9).reshape([3,3])
np_array_2d
a = np_array_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
np.sum(np_array_2d)
np.sum(np_array_2d, axis = 0) # Sum each columns
np.sum(np_array_2d, axis = 1) # Sum each rows

36

array([ 9, 12, 15])

array([ 3, 12, 21])

## Flatten

In [31]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## Transpose

In [32]:
a.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

## Boolean indexing

In [26]:
a < 2

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [27]:
a[a < 2]

array([0, 1])

## Slicing

In [30]:
a[-1] # Last line
a[:-1] # Remove last line
a[::-1] # Reverse lines
a[ : : -1] # Reverse lines
a[:,-1] # Last column
a[1,2] # Second line, third element
a[0:2,0:2] # only the first and second element of first and second line

array([6, 7, 8])

array([[0, 1, 2],
       [3, 4, 5]])

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

array([2, 5, 8])

5

array([[0, 1],
       [3, 4]])